---
- name: Install Visual Studio Code
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install command-line editors
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name:
      - nano
      - vim
    state: present

- name: Install Markdown editors
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name:
      - mark-text
      - obsidian

- name: Install pandoc
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: pandoc
