#!/usr/bin/env bash

ansible-playbook setup.yml --ask-become-pass "$@"

# Could not set the input sources using the Ansible’s dconf module, therefore
# the input sources are set using this script.
dconf write /org/gnome/desktop/input-sources/sources "[('xkb', 'us'), ('xkb', 'lt')]"
