---
- hosts: localhost
  roles:
    - role: users
      tags: users
    - role: base
      tags: base
    - role: editors
      tags: editors
    - role: browsers
      tags: browsers
    - role: security
      tags: security
    - role: storage
      tags: storage
    - role: dev-tools
      tags: dev-tools
    - role: productivity
      tags: productivity
    - role: communication
      tags: communication
    - role: peripherals
      tags: peripherals
    - role: learning
      tags: learning
    - role: media
      tags: media
    - role: phone
      tags: phone
