- name: Create the user {{ user_name }}
  become: true
  user:
    name: '{{ user_name }}'
    # justinas
    password: $6$mysecretsalt$u.SLHFJRv7zzTUMz.Qlz3tIqqh/An4KUOp49QYGqZWccadwYfOKT6T7ptHy8Gm4iPlfNUMEJAOsFPierEBE7z/
    update_password: on_create
    state: present
