- name: Install Java
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name:
      - openjdk@11
      - scala
    state: present

- name: Install Maven
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: maven
    state: present
