- name: Install a newer version of zsh
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
    state: present

- name: Add the path of the new zsh version to /etc/shells
  become: true
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
    state: present

- name: Change shell for current user
  become: true
  user:
    name: '{{ user_name }}'
    shell: /usr/local/bin/zsh
