- name: Update Homebrew and upgrade all packages
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install basic tools
  become: true
  become_user: '{{ user_name }}'
  homebrew_cask:
    name:
      - spectacle
      - hammerspoon
      - the-unarchiver
    state: present


- name: Install mas
  become: true
  become_user: '{{ user_name }}'
  homebrew:
    name: mas
